sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn install
script:
  - yarn test
  - yarn build
cache:
  yarn: true
  directories:
    - "node_modules"
