version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/equilab-web

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "e3:99:04:f1:71:29:87:18:96:8f:2d:a8:50:78:d5:b6"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn build

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git remote add dokku dokku@benjar.net:equilab
              git push dokku master
            fi
