version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/equilab-web

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn build

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'benjar.net ecdsa-sha2-nistp256 AAAAB3NzaC1yc2EAAAADAQABAAABAQC/lBfRAKMHq8JeXZsmeFghhtA2TWPhqDcZNFLXNKQjim2hugKXvqPb4iCccpiWHoT2hCHWOT55ODXDDrfEVTW7F/u3y3dIv8Dr9ueQ9sUaRW0OE00apEVrfcIEkVcazAQgVCwjt3RP7p7LN2qRxucAcZ/6/Irp737IZ/aTnSL5rjYS3UnolmJBTT206yWUxt88ensF2Nl60w6RDbfZlz2jREVz/ktNwtqAMzKomHEz3bZQO0tKv4//xsasVZCVomTYhQjEOr/52gkUadAkqnqpc1o1QjB5gsB96jyKE1KuWAutN/LZtcwav25vTiH5dv2oAXmdg3RsETLUXO6hbL8J' >> ~/.ssh/known_hosts
              git remote add dokku dokku@benjar.net:equilab
              git push dokku master
            fi
